"""Stable analysis lifecycle states exposed to API consumers."""

from enum import StrEnum


class AnalysisStageState(StrEnum):
    QUEUED = "QUEUED"
    PARSING = "PARSING"
    EXTRACTING = "EXTRACTING"
    AUTHENTICATION_ANALYSIS = "AUTHENTICATION_ANALYSIS"
    HEADER_ANALYSIS = "HEADER_ANALYSIS"
    URL_ANALYSIS = "URL_ANALYSIS"
    DOMAIN_ANALYSIS = "DOMAIN_ANALYSIS"
    IP_ANALYSIS = "IP_ANALYSIS"
    ATTACHMENT_ANALYSIS = "ATTACHMENT_ANALYSIS"
    CONTENT_ANALYSIS = "CONTENT_ANALYSIS"
    SCORING = "SCORING"
    TIMELINE = "TIMELINE"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
