"""initial schema

Revision ID: 38907ae8a829
Revises: 
Create Date: 2026-09-03 10:50:22.039232+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38907ae8a829'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('subject', sa.String(length=512), nullable=True),
    sa.Column('sender', sa.String(length=256), nullable=True),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('score_breakdown', sa.JSON(), nullable=False),
    sa.Column('analysis_warnings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigations_external_id'), ['external_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_investigations_sender'), ['sender'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigations_verdict'), ['verdict'], unique=False)

    op.create_table('ai_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('agent', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('input_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_audits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_audits_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('analysis_stages',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_stages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_stages_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_stages_stage'), ['stage'], unique=False)

    op.create_table('authentication_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('protocol', sa.String(length=16), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authentication_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authentication_results_investigation_id'), ['investigation_id'], unique=False)

    op.create_table('email_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('plain_body', sa.Text(), nullable=True),
    sa.Column('html_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_artifacts_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_artifacts_sha256'), ['sha256'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_evidence_type'), ['type'], unique=False)

    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence_refs', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_findings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_findings_severity'), ['severity'], unique=False)

    op.create_table('indicators',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=False),
    sa.Column('normalized_value', sa.Text(), nullable=False),
    sa.Column('threat_verdict', sa.String(length=32), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicators_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_normalized_value'), ['normalized_value'], unique=False)
        batch_op.create_index(batch_op.f('ix_indicators_type'), ['type'], unique=False)

    op.create_table('received_hops',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('hop_number', sa.Integer(), nullable=False),
    sa.Column('from_host', sa.String(length=256), nullable=True),
    sa.Column('by_host', sa.String(length=256), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('received_hops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_received_hops_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_received_hops_ip_address'), ['ip_address'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('time_kind', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_investigation_id'), ['investigation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('artifact_attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('extension', sa.String(length=32), nullable=True),
    sa.Column('is_suspicious', sa.Boolean(), nullable=False),
    sa.Column('magic_bytes', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['artifact_id'], ['email_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artifact_attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_attachments_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_artifact_attachments_sha256'), ['sha256'], unique=False)

    op.create_table('email_headers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['email_artifacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_headers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_headers_artifact_id'), ['artifact_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_headers_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_headers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_headers_name'))
        batch_op.drop_index(batch_op.f('ix_email_headers_artifact_id'))

    op.drop_table('email_headers')
    with op.batch_alter_table('artifact_attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_attachments_sha256'))
        batch_op.drop_index(batch_op.f('ix_artifact_attachments_artifact_id'))

    op.drop_table('artifact_attachments')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_investigation_id'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('received_hops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_received_hops_ip_address'))
        batch_op.drop_index(batch_op.f('ix_received_hops_investigation_id'))

    op.drop_table('received_hops')
    with op.batch_alter_table('indicators', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicators_type'))
        batch_op.drop_index(batch_op.f('ix_indicators_normalized_value'))
        batch_op.drop_index(batch_op.f('ix_indicators_investigation_id'))

    op.drop_table('indicators')
    with op.batch_alter_table('findings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_findings_severity'))
        batch_op.drop_index(batch_op.f('ix_findings_investigation_id'))
        batch_op.drop_index(batch_op.f('ix_findings_category'))

    op.drop_table('findings')
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evidence_type'))
        batch_op.drop_index(batch_op.f('ix_evidence_investigation_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('email_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_artifacts_sha256'))
        batch_op.drop_index(batch_op.f('ix_email_artifacts_investigation_id'))

    op.drop_table('email_artifacts')
    with op.batch_alter_table('authentication_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authentication_results_investigation_id'))

    op.drop_table('authentication_results')
    with op.batch_alter_table('analysis_stages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_stages_stage'))
        batch_op.drop_index(batch_op.f('ix_analysis_stages_investigation_id'))

    op.drop_table('analysis_stages')
    with op.batch_alter_table('ai_audits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_audits_investigation_id'))

    op.drop_table('ai_audits')
    with op.batch_alter_table('investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigations_verdict'))
        batch_op.drop_index(batch_op.f('ix_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_investigations_sender'))
        batch_op.drop_index(batch_op.f('ix_investigations_external_id'))

    op.drop_table('investigations')
    # ### end Alembic commands ###